iata_to_city_map = {
    "DEL": "New Delhi",
    "BOM": "Mumbai",
    "MAA": "Chennai",
    "CCU": "Kolkata",
    "BLR": "Bangalore",
    "HYD": "Hyderabad",
    "GOI": "Goa",
    "COK": "Kochi",
    "AMD": "Ahmedabad",
    "PNQ": "Pune",
    "JAI": "Jaipur",
    "LKO": "Lucknow",
    "GAU": "Guwahati",
    "VNS": "Varanasi",
    "IDR": "Indore",
    "PAT": "Patna",
    "NAG": "Nagpur",
    "STV": "Surat",
    "IXC": "Chandigarh",
    "BHO": "Bhopal",
    "RPR": "Raipur",
    "IXR": "Ranchi",
    "BBI": "Bhubaneswar",
    "VTZ": "Visakhapatnam",
    "CJB": "Coimbatore",
    "TRV": "Thiruvananthapuram",
    "IXM": "Madurai",
    "ATQ": "Amritsar",
    "SXR": "Srinagar",
    "IXJ": "Jammu",
    "DED": "Dehradun",
    "AGR": "Agra",
    "KNU": "Kanpur",
    "IXE": "Mangalore",
    "TRZ": "Tiruchirappalli",
    "BDQ": "Vadodara",
    "RAJ": "Rajkot",
    "JDH": "Jodhpur",
    "UDR": "Udaipur",
    "IXU": "Aurangabad",
    "GAY": "Gaya",
    "JLR": "Jabalpur",
    "IXL": "Leh",
    "IMF": "Imphal",
    "AJL": "Aizawl",
    "SHL": "Shillong",
    "DMU": "Dimapur",
    "IXA": "Agartala",
    "IXS": "Silchar",
    "DIB": "Dibrugarh",
    "IXZ": "Port Blair",
    "TEZ": "Tezpur",
    "TCR": "Tuticorin",
    "HBX": "Hubli",
    "IXG": "Belgaum",
    "KLH": "Kolhapur",
    "JGA": "Jamnagar",
    "BHU": "Bhavnagar",
    "IXY": "Kandla",
    "DIU": "Diu",
    "PNY": "Pondicherry",
    "IXT": "Pasighat",
    "KUU": "Kullu",
    "PGH": "Pantnagar",
    "BHJ": "Bhuj",
    "SAG": "Shirdi",
    "SDW": "Sindhudurg",
    "JRH": "Jorhat",
    "ZER": "Zero",
    "IXI": "Lilabari",
    "KQH": "Kishangarh",
    "RUP": "Rupsi"
}

def resolve_city_from_iata(iata_code: str) -> str:
    return iata_to_city_map.get(iata_code.upper(), iata_code.upper())
